### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by montyclt** [TriggerMe/CSharpVatChecker#1]
Will this library publish in NuGet?

**Comment by jamesikanos** [comment]
Yes, when the TriggerMe service goes live. Contact me at james[at]triggerme.io for early access if you're interested?

**Comment by montyclt** [comment]
While the VATChecker is lincensed under MIT, I copied the source code to a class in my project and I'm using it directly.

When the package goes into NuGet, I'll deleted my local class and install it.

**Comment by jamesikanos** [comment]
FYI, there is now a NuGet package. Happy coding. 

https://www.nuget.org/packages/TriggerMe.VATChecker
