### ISSUE TITLE
Update link

### ISSUE THREAD

**Issue by punthoofd07** [TriggerMe/CSharpVatChecker#3]
Hello, 

Thanks for the library. Could you please update the link from http to https? This to make sure there is no mixed content while writing web apps. 

Many thanks!

**Comment by jamesikanos** [comment]
Hi there,

Good spot. At the time of writing, https did not work. I'm not too sure if it does now.

By all means, please submit a PR as I'm not in a position at the moment myself to update.

**Comment by punthoofd07** [comment]
Hi, 
It doesn't work. I solved it by putting it behind an Azure Function (API call). 
Thanks for the library!!

**Comment by jamesikanos** [comment]
Oh dear, it's shame that 2 years on it still doesn't support HTTPS. Thanks for trying.
